# Generated by Django 4.0.3 on 2022-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=100)),
                ('breed', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('weight', models.IntegerField()),
                ('days_in_shelter', models.IntegerField()),
                ('days_left', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
