# Generated by Django 4.0.3 on 2022-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='animal',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
