# Generated by Django 4.0.3 on 2022-04-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_animal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='img',
            new_name='image',
        ),
    ]
