# Generated by Django 4.0.3 on 2022-04-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_animal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='user',
            new_name='favorites',
        ),
    ]
