# Generated by Django 4.0.3 on 2022-04-07 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_user_animal_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
