# Generated by Django 4.0.3 on 2022-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_animal_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shelter_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
