# Generated by Django 4.0.3 on 2022-04-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.shelter'),
            preserve_default=False,
        ),
    ]
