# Generated by Django 4.0.3 on 2022-04-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_shelter_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='days_left',
            new_name='due_date',
        ),
    ]
