# Generated by Django 4.0.3 on 2022-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
