# Generated by Django 4.0.3 on 2022-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_animal_age_alter_animal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='kill',
            field=models.CharField(choices=[('Kill', 'Kill'), ('No-kill', 'No-kill')], max_length=10),
        ),
    ]
