# Generated by Django 4.0.3 on 2022-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_animal_sex_alter_shelter_kill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(max_length=250),
        ),
    ]
