# Generated by Django 4.0.3 on 2022-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_animal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
